from django.urls import path
from .views import (
    AdminDashboardView,
    AdminReservationListView,
    AdminReservationDetailView,
    TableListView,
    TableCreateView,
    TableUpdateView,
    FoodListView,
    FoodCreateView,
    FoodUpdateView,
    FoodDeleteView,
    CategoryListView,
    CategoryCreateView,
    CategoryUpdateView,
    CafeSettingsView,
    GenerateSlotsView,
    ClearSlotsView,
    WorkingHoursListView,
    WorkingHourUpdateView,
    DiscountListView,
    DiscountCreateView,
    DiscountUpdateView,
    DiscountDeleteView,
    CategoryDeleteView,
    TableDeleteView
)

urlpatterns = [
    path("", AdminDashboardView.as_view(), name="dashboard"),
    path("reservations/", AdminReservationListView.as_view(), name="reservations"),
    path("reservations/<int:pk>/", AdminReservationDetailView.as_view(), name="admin_reservation_detail"),
    path("tables/", TableListView.as_view(), name="tables"),
    path("tables/add/", TableCreateView.as_view(), name="table_add"),
    path(
    "tables/<int:pk>/delete/", TableDeleteView.as_view(), name="table_delete"),
    path("tables/<int:pk>/edit/", TableUpdateView.as_view(), name="table_edit"),
    path("food/", FoodListView.as_view(), name="food"),
    path("food/add/", FoodCreateView.as_view(), name="food_add"),
    path("food/<int:pk>/edit/", FoodUpdateView.as_view(), name="food_edit"),
    path("food/<int:pk>/delete/", FoodDeleteView.as_view(), name="food_delete"),
    path("categories/", CategoryListView.as_view(), name="categories"),
    path("categories/add/", CategoryCreateView.as_view(), name="category_add"),
    path(
    "categories/<int:pk>/delete/", CategoryDeleteView.as_view(), name="category_delete",),
    path("categories/<int:pk>/edit/", CategoryUpdateView.as_view(), name="category_edit"),
    path("settings/", CafeSettingsView.as_view(), name="settings"),
    path("slots/generate/", GenerateSlotsView.as_view(), name="generate_slots"),
    path("slots/clear/", ClearSlotsView.as_view(), name="clear_slots"),
    path("working-hours/", WorkingHoursListView.as_view(), name="working_hours"),
    path("working-hours/<int:pk>/edit/", WorkingHourUpdateView.as_view(), name="working_hour_edit"),
    path("discounts/", DiscountListView.as_view(), name="discounts"),
    path("discounts/add/", DiscountCreateView.as_view(), name="discount_add"),
    path("discounts/<int:pk>/edit/", DiscountUpdateView.as_view(), name="discount_edit"),
    path("discounts/<int:pk>/delete/", DiscountDeleteView.as_view(), name="discount_delete"),
]