# Generated by Django 6.0.1 on 2026-01-25 23:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('seating', '0002_alter_cafetable_capacity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Reservation Date')),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('CON', 'Confirmed'), ('CAN', 'Cancelled'), ('COM', 'Compeleted')], default='PEN', max_length=3, verbose_name='Reservation Status')),
                ('attendance_status', models.CharField(choices=[('UNK', 'Unknown'), ('PRE', 'Present'), ('ABS', 'Absent')], default='UNK', max_length=3, verbose_name='Attendance Status')),
                ('number_of_people', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of People')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Write Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='seating.cafetable', verbose_name='Table')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='seating.timeslot', verbose_name='Time Slot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('final_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Final Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Write Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_foods', to='menu.fooditem', verbose_name='Food Item')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_foods', to='reservations.reservation', verbose_name='Reservation')),
            ],
        ),
    ]
