# Generated by Django 6.0.2 on 2026-02-05 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options'),
        ('reservations', '0002_alter_reservation_total_price_review_reviewreply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewreply',
            options={'verbose_name_plural': 'Review Replies'},
        ),
        migrations.AlterField(
            model_name='reviewreply',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_replies', to=settings.AUTH_USER_MODEL, verbose_name='Admin'),
        ),
        migrations.AddConstraint(
            model_name='reservationfood',
            constraint=models.UniqueConstraint(fields=('reservation', 'food_item'), name='unique_food_per_reservation'),
        ),
    ]
