# Generated by Django 6.0.1 on 2026-02-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, max_length=256, verbose_name='Notes'),
        ),
    ]
