# Generated by Django 6.0.1 on 2026-02-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('CON', 'Confirmed'), ('CAN', 'Canceled'), ('COM', 'Compeleted')], default='PEN', max_length=3, verbose_name='Reservation Status'),
        ),
    ]
