# Generated by Django 6.0.1 on 2026-04-08 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation', verbose_name='Reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('CON', 'Confirmed'), ('CAN', 'Cancelled'), ('COM', 'Completed')], default='PEN', max_length=3, verbose_name='Reservation Status'),
        ),
    ]
