# Generated by Django 6.0.1 on 2026-02-20 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_comment_id_alter_reply_id_alter_reservation_id_and_more'),
        ('reservations', '0003_reservation_notes'),
    ]

    operations = [
    ]
