# Generated by Django 6.0.2 on 2026-02-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reviewreply_admin'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservationfood',
            name='unique_food_per_reservation',
        ),
    ]
