# Generated by Django 6.0.1 on 2026-02-01 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_reservation_is_deleted_reservationfood_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='time_slot',
        ),
        migrations.RenameModel(
            old_name='Review',
            new_name='Comment',
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('reply', models.TextField(max_length=256, verbose_name='Reply')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Write Time')),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_replies', to='reservations.comment', verbose_name='Review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_replies', to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
            ],
            options={
                'verbose_name_plural': 'Review Replies',
            },
        ),
        migrations.DeleteModel(
            name='ReviewReply',
        ),
    ]
