# Generated by Django 6.0.5 on 2026-05-20 22:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_alter_reply_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={},
        ),
        migrations.AddConstraint(
            model_name='reply',
            constraint=models.UniqueConstraint(fields=('comment',), name='one_reply_per_comment'),
        ),
    ]
