# Generated by Django 6.0.1 on 2026-02-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_window_hours', models.PositiveIntegerField(default=1)),
                ('allow_user_cancel', models.BooleanField(default=True)),
                ('allow_admin_late_cancel', models.BooleanField(default=True)),
                ('reservations_enabled', models.BooleanField(default=True)),
                ('slot_duration_minutes', models.PositiveIntegerField(default=120)),
                ('auto_generate_days_ahead', models.PositiveIntegerField(default=7)),
            ],
        ),
    ]
