# Generated by Django 6.0.2 on 2026-02-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
