# Generated by Django 6.0.1 on 2026-01-31 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_category_is_deleted_fooditem_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('discount_type', models.CharField(choices=[('PER', 'Percent'), ('FIX', 'Fixed amount')], max_length=3, verbose_name='Type')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Write Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='menu.discount', verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='discount',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='menu.discount', verbose_name='Discount'),
        ),
    ]
