# Generated by Django 6.0.1 on 2026-02-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='date',
            field=models.DateField(default='2025-01-01', verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Table'),
        ),
        migrations.AlterField(
            model_name='cafetable',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('date', 'table', 'start_time', 'end_time')},
        ),
    ]
