# Generated by Django 6.0.1 on 2026-02-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghour',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Is Closed'),
        ),
    ]
