# Generated by Django 6.0.1 on 2026-01-25 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafetable',
            name='capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='cafetable',
            name='price_per_person',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price (Per Person)'),
        ),
        migrations.AlterField(
            model_name='cafetable',
            name='table_number',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Table Number'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='duration_minutes',
            field=models.PositiveIntegerField(editable=False, verbose_name='Duration (In Minutes)'),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='day_of_week',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3, unique=True, verbose_name='Day of Week'),
        ),
    ]
