# Generated by Django 6.0.1 on 2026-02-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0002_timeslot_date_timeslot_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=models.DateField(default='0000/00/00', verbose_name='Date'),
        ),
    ]
