# Generated by Django 6.0.2 on 2026-02-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0002_alter_cafetable_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafetable',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workinghour',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
