# Generated by Django 6.0.1 on 2026-04-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0002_workinghour_is_closed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('table', 'date', 'start_time', 'end_time')},
        ),
    ]
