# Generated by Django 6.0.1 on 2026-02-01 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0003_cafetable_is_deleted_timeslot_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='seating.cafetable', verbose_name='Table'),
        ),
    ]
