# Generated by Django 6.0.1 on 2026-02-01 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0004_timeslot_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='seating.cafetable', verbose_name='Table'),
        ),
    ]
