# Generated by Django 6.0.1 on 2026-02-10 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0005_alter_timeslot_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 2, 10, 8, 0, 29, 574038), verbose_name='Date'),
        ),
    ]
