# Generated by Django 6.0.1 on 2026-02-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0009_alter_timeslot_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
