# Generated by Django 6.0.1 on 2026-02-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0010_alter_timeslot_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
